Task7
Lejdis500/invoicing-system-patrycja-wojcik pull request #10
Opened 2023-08-09 18:23 UTC by Lejdis500

2023-08-09 18:37 UTC, BartoszKamyszek requested changes

2023-08-09 18:37 UTC, BartoszKamyszek commented on .github/workflows/main.yaml
> +          distribution: 'temurin'
spróbuj zulu zamiast temurin

2023-08-09 18:39 UTC, Lejdis500 commented on .github/workflows/main.yaml
> +          distribution: 'temurin'
Przeszlo :)

2023-08-09 18:40 UTC, BartoszKamyszek approved these changes, later dismissed

2023-08-17 19:20 UTC, strzeleckik approved these changes
ok

2023-10-18 18:42 UTC, BartoszKamyszek approved these changes

2023-10-18 18:42 UTC, merged